- name: nginx installation
  hosts: web
  become: yes
  tasks:
    - name: now we are installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: now we are starting the nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
