- name: installing Nginx 
  hosts: localhost
  become: yes # equal to -b in adhoc commands, getting root access
  tasks:
    - name: first install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
        
    - name: after starting nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

